version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  test_and_build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Test
          command: npm run coverage
      - run:
          name: Build
          command: npm run compile

workflows:
  test_and_build:
    jobs:
      - test_and_build
